//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaturaDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fatura
    {
        public int faturaID { get; set; }
        public int aboneNo { get; set; }
        public Nullable<decimal> faturaTutari { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public Nullable<System.DateTime> sonOdemeTarihi { get; set; }
        public Nullable<System.DateTime> faturaOdemeTarihi { get; set; }
        public Nullable<bool> faturaDurumu { get; set; }
    }
}
