//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaturaDataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AskiDatabaseEntities : DbContext
    {
        public AskiDatabaseEntities()
            : base(@"metadata = res://*/FaturaServisModel.csdl|res://*/FaturaServisModel.ssdl|res://*/FaturaServisModel.msl;provider=System.Data.SqlClient;provider connection string=';data source=tcp:server-bank.database.windows.net,1433;initial catalog=AskiDatabase;Persist Security Info=False;user id=adminBank;password=bank+App;MultipleActiveResultSets=True;App=EntityFramework&quot';")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Fatura> Fatura { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
