//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hesap
    {
        public int hesapNo { get; set; }
        public Nullable<decimal> bakiye { get; set; }
        public Nullable<System.DateTime> hesapAcilisTarihi { get; set; }
        public Nullable<int> musteriNo { get; set; }
        public Nullable<int> acilisPlatformID { get; set; }
        public Nullable<int> ekNo { get; set; }
    
        public virtual AcilisPlatformu AcilisPlatformu { get; set; }
        public virtual Musteri Musteri { get; set; }
    }
}
