//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Musteri()
        {
            this.Hesap = new HashSet<Hesap>();
        }
    
        public int musteriNo { get; set; }
        public string tckn { get; set; }
        public string sifre { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public Nullable<System.DateTime> dogumTarihi { get; set; }
        public string cepTelefonu { get; set; }
        public string mail { get; set; }
        public string acikAdres { get; set; }
        public Nullable<System.DateTime> kayıtTarihi { get; set; }
        public Nullable<int> acilisPlatformID { get; set; }
    
        public virtual AcilisPlatformu AcilisPlatformu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hesap> Hesap { get; set; }
    }
}
